name: Code Quality

on:
  workflow_call:  # Allows this workflow to be called from ci.yaml
  workflow_dispatch:  # Allows this workflow to be manually called from GitHub UI

jobs:
  lint:
    name: Lint (Ruff)
    runs-on: ubuntu-24.04
    timeout-minutes: 6

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-python-uv-action
        timeout-minutes: 5

      - name: Run Ruff linter
        run: uv run ruff check .

  format:
    name: Format (Ruff)
    runs-on: ubuntu-24.04
    timeout-minutes: 6

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-python-uv-action
        timeout-minutes: 5

      - name: Check code formatting
        run: uv run ruff format . --check

  type-check:
    name: Type Check (Mypy)
    runs-on: ubuntu-24.04
    timeout-minutes: 6

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-python-uv-action
        timeout-minutes: 5

      - name: Run Mypy static type checking
        run: uv run mypy .
